export const ALL_TOOLS: ToolItem[] = [
  // --- Featured High Intent Traffic ---
  {
    id: "govt-job-photo-resizer",
    name: "Govt Exam Photo & Signature Resizer",
    description: "Resize photos & signatures by exact KB limits and dimensions for SSC, UPSC, MPSC & Banking forms.",
    category: "image",
    href: "/tools/govt-job-photo-resizer",
    icon: UserCheck,
    isPopular: true,
    isTrending: true,
    badge: "EXAM TOOL",
    gradient: "from-emerald-500/10 to-teal-500/10 border-emerald-500/30 text-emerald-400",
  },
  {
    id: "pdf-compressor",
    name: "Target Size PDF Compressor",
    description: "Compress PDFs to exact target KB limits directly inside browser RAM without remote server uploads.",
    category: "pdf",
    href: "/tools/pdf-compressor",
    icon: FileText,
    isPopular: true,
    badge: "KB Optimizer",
    gradient: "from-emerald-500/10 to-cyan-500/10 border-emerald-500/30 text-emerald-400",
  },
  {
    id: "pdf-merge",
    name: "Merge PDF Suite",
    description: "Combine multiple PDF documents into one organized file with custom sequence ordering.",
    category: "pdf",
    href: "/tools/pdf-merge",
    icon: Combine,
    isPopular: true,
    badge: "Most Used",
    gradient: "from-blue-500/10 to-indigo-500/10 border-blue-500/30 text-blue-400",
  },
  {
    id: "jpg-to-pdf",
    name: "JPG / Image to PDF",
    description: "Transform scans, gallery photos, and graphics into a single unified multi-page PDF document.",
    category: "converters",
    href: "/tools/jpg-to-pdf",
    icon: RefreshCw,
    isPopular: true,
    badge: "Multi-Image",
    gradient: "from-emerald-500/10 to-teal-500/10 border-emerald-500/30 text-emerald-400",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image (JPG)",
    description: "Extract and render each PDF page into high-resolution JPG images with retina clarity.",
    category: "converters",
    href: "/tools/pdf-to-image",
    icon: ImageIcon,
    isPopular: true,
    badge: "Most Used",
    gradient: "from-emerald-500/10 to-teal-500/10 border-emerald-500/30 text-emerald-400",
  },
  {
    id: "image-compressor",
    name: "Target Size Image Compressor",
    description: "Compress JPG, PNG, and WebP assets to exact KB targets using client-side image quantization.",
    category: "image",
    href: "/tools/image-compressor",
    icon: Crop,
    isPopular: true,
    badge: "Batch Mode",
    gradient: "from-amber-500/10 to-orange-500/10 border-amber-500/30 text-amber-400",
  },
  // Baki saare tools waise hi rahenge...
];